export class Seats {
  busComapny:string = "Mahalaxmi";
  busName:string = "Super Deluxe";
  date:string = "2023-07-11";
  lC1:boolean = false;
  lC2:boolean = false;
  lC3:boolean = false;
  lC4:boolean = false;
  lC5:boolean = false;
  lC6:boolean = false;
  lC7:boolean = false;
  lC8:boolean = false;
  lC9:boolean = false;
  lC10:boolean = false;
  lC11:boolean = false;
  lC12:boolean = false;
  lC13:boolean = false;
  lC14:boolean = false;
  lC15:boolean = false;
  lC16:boolean = false;
  lC17:boolean = false;
  lC18:boolean = false;
  lC19:boolean = false;
  lC20:boolean = false;
  lC21:boolean = false;
  lC22:boolean = false;
  lC23:boolean = false;
  lC24:boolean = false;
}
